### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by azarezade** [hadim/docker-tensorflow-builder#4]
I failed building wheel in ubuntu with the following env variables:
```
export PYTHON_VERSION=3.6
export TF_VERSION_GIT_TAG=v1.11.0
export USE_GPU=0
```
after about 3 hour building I get this error:
```
...
In file included from tensorflow/contrib/lite/kernels/slice.cc:21:0:
./tensorflow/contrib/lite/kernels/internal/optimized/optimized_ops.h: In function 'void tflite::optimized_ops::LogSoftmax(const uint8*, const tflite::RuntimeShape&, int32, int32, int32, int32, int, uint8*, const tflite::RuntimeShape&)':
./tensorflow/contrib/lite/kernels/internal/optimized/optimized_ops.h:4498:53: warning: typedef 'using FixedPoint0 = class gemmlowp::FixedPoint<int, 0>' locally defined but not used [-Wunused-local-typedefs]
   using FixedPoint0 = gemmlowp::FixedPoint<int32, 0>;
                                                     ^
In file included from ./tensorflow/contrib/lite/builtin_op_data.h:20:0,
                 from tensorflow/contrib/lite/kernels/slice.cc:19:
tensorflow/contrib/lite/kernels/slice.cc: In function 'TfLiteStatus tflite::ops::builtin::slice::Prepare(TfLiteContext*, TfLiteNode*)':
tensorflow/contrib/lite/kernels/slice.cc:115:48: warning: suggest parentheses around comparison in operand of '==' [-Wparentheses]
   TF_LITE_ENSURE(context, NumDimensions(begin) == NumDimensions(size) == 1);
                                                ^
./tensorflow/contrib/lite/context.h:119:11: note: in definition of macro 'TF_LITE_ENSURE'
     if (!(a)) {                                                             \
           ^
ERROR: /tensorflow/tensorflow/BUILD:592:1: Executing genrule //tensorflow:tensorflow_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import applications
  File "/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/applications/__init__.py", line 22, in <module>
    import keras_applications
ModuleNotFoundError: No module named 'keras_applications'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9175.670s, Critical Path: 94.40s
INFO: 5604 processes: 5604 local.
FAILED: Build did NOT complete successfully
```

**Comment by hadim** [comment]
At https://github.com/hadim/docker-tensorflow-builder/blob/master/tensorflow/ubuntu-16.04/build.sh#L15, you can try to add `keras_applications` or add a command to pip-install it of it's not in conda-forge.

If it works, a PR is welcome.

**Comment by azarezade** [comment]
thanks @hadim , adding `conda install -c conda-forge keras-applications` to `build.sh` worked
